version: '3.0'

services:
  mongo:
    image: mongo:4.1.10
    ports:
      - '27017:27017'
  emailer:
    image: emailer
    build: .
    ports:
      - 8888:8888
    depends_on:
      - mongo
    env_file:
      - dev.env
